"""Git hook integration for auto-indexing."""

import os
import shutil
import stat
from pathlib import Path

from rich.console import Console


def install_githook(console: Console, hook_type: str = "post-commit") -> None:
    """Install git hook for auto-indexing."""
    git_dir = Path.cwd() / ".git"
    hooks_dir = git_dir / "hooks"
    
    if not git_dir.exists():
        console.print("[red]Not a git repository[/red]")
        return
    
    hooks_dir.mkdir(parents=True, exist_ok=True)
    
    hook_content = f"""#!/bin/sh
# CortexCode auto-index hook
# Generated by cortexcode githook install

# Only run on post-commit
if [ "$CORTEXCODE_HOOK" != "post-commit" ]; then
    exit 0
fi

# Check if index exists
if [ -f ".cortexcode/index.json" ]; then
    # Only re-index if there were changes to code files
    CHANGED_FILES=$(git diff-tree -r --name-only --no-commit-id HEAD~1 HEAD -- "*.py" "*.js" "*.ts" "*.jsx" "*.tsx" "*.go" "*.rs" "*.java" "*.cs" 2>/dev/null)
    if [ -n "$CHANGED_FILES" ]; then
        cortexcode index -i 2>/dev/null || true
    fi
fi
"""
    
    hook_path = hooks_dir / hook_type
    hook_path.write_text(hook_content)
    
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    console.print(f"[green]✓[/green] Installed {hook_type} hook at {hook_path}")
    console.print(f"[dim]Run 'CORTEXCODE_HOOK=post-commit git commit ...' to trigger auto-index[/dim]")


def uninstall_githook(console: Console, hook_type: str = "post-commit") -> None:
    """Remove git hook."""
    git_dir = Path.cwd() / ".git"
    hook_path = git_dir / "hooks" / hook_type
    
    if hook_path.exists():
        hook_path.unlink()
        console.print(f"[green]✓[/green] Removed {hook_type} hook")
    else:
        console.print(f"[yellow]No {hook_type} hook found[/yellow]")


def install_pre_commit(console: Console) -> None:
    """Install pre-commit hook for code quality checks."""
    git_dir = Path.cwd() / ".git"
    hooks_dir = git_dir / "hooks"
    
    if not git_dir.exists():
        console.print("[red]Not a git repository[/red]")
        return
    
    hooks_dir.mkdir(parents=True, exist_ok=True)
    
    hook_content = """#!/bin/sh
# CortexCode pre-commit hook
# Runs security scan before commit

# Run security scan on staged files
STAGED_PY=$(git diff --cached --name-only --diff-filter=ACM | grep '\\.py$' | head -10)
if [ -n "$STAGED_PY" ]; then
    echo "Running CortexCode security scan..."
    cortexcode scan 2>/dev/null | head -20
fi
"""
    
    hook_path = hooks_dir / "pre-commit"
    hook_path.write_text(hook_content)
    
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    
    console.print(f"[green]✓[/green] Installed pre-commit hook")
    console.print(f"[dim]Security scan will run before each commit[/dim]")


def handle_githook_install(console: Console, hook_type: str) -> None:
    """CLI handler for githook install."""
    install_githook(console, hook_type)


def handle_githook_uninstall(console: Console, hook_type: str) -> None:
    """CLI handler for githook uninstall."""
    uninstall_githook(console, hook_type)


def handle_githook_precommit(console: Console) -> None:
    """CLI handler for pre-commit install."""
    install_pre_commit(console)
