DEFAULT_IGNORE_PATTERNS = {
    "__pycache__", ".venv", "venv", "env", ".env", "virtualenv",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox", ".nox",
    "*.egg-info", ".eggs", "*.pyc", "*.pyo",
    "node_modules", ".npm", ".yarn", ".pnpm-store", "bower_components",
    "dist", "build", "out", "output", "target", "bin", "obj",
    ".build", "_build", "public/build", "lib",
    ".next", ".nuxt", ".svelte-kit", ".angular", ".turbo",
    ".parcel-cache", ".webpack", ".rollup.cache", ".vite",
    ".expo", ".gradle", "Pods", "DerivedData",
    ".idea", ".vscode", ".vs", "*.sublime-*",
    ".git", ".svn", ".hg",
    ".cache", ".tmp", "tmp", "temp", ".temp",
    "coverage", ".nyc_output", ".jest",
    ".cortexcode",
    "*.log", ".env.local", ".DS_Store", "Thumbs.db",
    "vendor", "third_party", "external", "deps",
    "__tests__", "__mocks__", "test_fixtures",
    ".serverless", ".terraform", ".pulumi",
    "android/app/build", "ios/build", "ios/Pods",
}
